### ISSUE TITLE
Chapter 8 TODO

### ISSUE THREAD

**Issue by ChJus** [JC-ProgJava/Building-Neural-Networks-From-Scratch#31]
- [x] Upload chapter to web
- [x] Upload clean and commented code
- [x] Update citation list
